apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-api-proxy.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events {}
        stream {
        server {
            listen 443;
            proxy_pass kubernetes.default.svc:443;
        }
    }
