apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "kube-api-proxy.fullname" . }}-secret
  namespace: kube-system
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsCrt | quote }}
  tls.key: {{ .Values.tlsKey | quote }}