apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-api-proxy.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 443 ssl;
        ssl_certificate     /etc/nginx/tls/tls.crt;
        ssl_certificate_key /etc/nginx/tls/tls.key;
        location / {
          proxy_pass https://kubernetes.default.svc;
          proxy_ssl_verify off;
        }
      }
    }

