apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: ${nodeclass_name}
spec:
  amiFamily: AL2
  role: "${karpenter_node_role_name}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: e6data-${cluster_name}
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: e6data-${cluster_name}
  tags: ${tags}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: ${volume_size}
        volumeType: gp3