apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: e6data-nodepool
spec:
  template:
    metadata:
      labels:
        app: e6data
        e6data-workspace-name: ${workspace_name}
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["us-east-1b","us-east-1c","us-east-1d","us-east-1a","us-east-1e"]
      nodeClassRef:
        name: e6data-nodeclass-${workspace_name}
  limits:
    cpu: 100000
  disruption:
    consolidationPolicy: WhenUnderutilized
