apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: e6data-nodeclass-${workspace_name}
spec:
  amiFamily: AL2
  role: "${karpenter_node_role_name}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: e6data-${cluster_name}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: e6data-${cluster_name}
  tags:
    App: "e6data"
    Environment: "Dev"
    Operation: "POC"
    Team: "PLT"
    User: "harshith@e6x.io"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
        volumeType: gp3
