apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: ${nodeclass_name}
spec:
  amiFamily: AL2
  role: "${karpenter_node_role_name}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: e6data-${cluster_name}
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: e6data-${cluster_name}
  tags: ${tags}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: ${volume_size}Gi
        volumeType: gp3
userData: |
  IyEvYmluL2Jhc2gKeXVtIGluc3RhbGwgbnZtZS1jbGkgLXkKaWYgbnZtZSBsaXN0IHwgZ3JlcCAtcSAiQW1hem9uIEVDMiBOVk1lIEluc3RhbmNlIFN0b3JhZ2UiOyB0aGVuCiAgICBudm1lX2RyaXZlcz0kKG52bWUgbGlzdCB8IGdyZXAgIkFtYXpvbiBFQzIgTlZNZSBJbnN0YW5jZSBTdG9yYWdlIiB8IGN1dCAtZCAiICIgLWYgMSB8fCB0cnVlKQogICAgcmVhZGFycmF5IC10IG52bWVfZHJpdmVzIDw8PCAiJG52bWVfZHJpdmVzIgogICAgbnVtX2RyaXZlcz0keyNudm1lX2RyaXZlc1tAXX0KICAgIGlmIFsgJG51bV9kcml2ZXMgLWd0IDEgXTsgdGhlbgogICAgICAgIHl1bSBpbnN0YWxsIG1kYWRtIC15CiAgICAgICAgbWRhZG0gLS1jcmVhdGUgL2Rldi9tZDAgLS1sZXZlbD0wIC0tbmFtZT1tZDAgLS1yYWlkLWRldmljZXM9JG51bV9kcml2ZXMgIiR7bnZtZV9kcml2ZXNbQF19IgogICAgICAgIG1rZnMuZXh0NCAvZGV2L21kMAogICAgICAgIHV1aWQ9JChibGtpZCAtbyB2YWx1ZSAtcyBVVUlEIC9kZXYvbWQwKQogICAgICAgIG1vdW50X2xvY2F0aW9uPSIvbW50L2Zhc3QtZGlza3MvJHV1aWQiCiAgICAgICAgbWtkaXIgLXAgJG1vdW50X2xvY2F0aW9uCiAgICAgICAgbW91bnQgL2Rldi9tZDAgJG1vdW50X2xvY2F0aW9uCiAgICAgICAgbWRhZG0gLS1kZXRhaWwgLS1zY2FuID4+IC9ldGMvbWRhZG0uY29uZgogICAgICAgIGVjaG8gL2Rldi9tZDAgJG1vdW50X2xvY2F0aW9uIGV4dDQgZGVmYXVsdHMsbm9hdGltZSAwIDIgPj4gL2V0Yy9mc3RhYgogICAgZWxzZQogICAgICAgIGZvciBkaXNrIGluICIke252bWVfZHJpdmVzW0BdfSIKICAgICAgICBkbwogICAgICAgICAgICBta2ZzLmV4dDQgLUYgJGRpc2sKICAgICAgICAgICAgdXVpZD0kKGJsa2lkIC1vIHZhbHVlIC1zIFVVSUQgJGRpc2spCiAgICAgICAgICAgIG1vdW50X2xvY2F0aW9uPSIvbW50L2Zhc3QtZGlza3MvJHt1dWlkfSIKICAgICAgICAgICAgbWtkaXIgLXAgJG1vdW50X2xvY2F0aW9uCiAgICAgICAgICAgIG1vdW50ICRkaXNrICRtb3VudF9sb2NhdGlvbgogICAgICAgICAgICBlY2hvICRkaXNrICRtb3VudF9sb2NhdGlvbiBleHQ0IGRlZmF1bHRzLG5vYXRpbWUgMCAyID4+IC9ldGMvZnN0YWIKICAgICAgICBkb25lCiAgICBmaQplbHNlCiAgICBlY2hvICJObyBOVk1lIGRyaXZlcyBkZXRlY3RlZC4gU2tpcHBpbmcgTlZNZS1zcGVjaWZpYyBjb21tYW5kcy4iCmZp