apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ${nodeclass_name}
  labels:
    app: e6data
    e6data-workspace-name: ${workspace_name}
spec:
  amiFamily: AL2
  amiSelectorTerms:
    - alias: al2@latest
  role: "${karpenter_node_role_name}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: ${cluster_name}
  tags: ${tags}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: ${volume_size}Gi
        volumeType: gp3
