name: test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - uat
          - beta
          - pilot
          - staging
          - prod
      workspace_name:
        description: 'Workspace Name'
        required: true
        type: string
      cluster_name:
        description: 'New EKS Cluster Name'
        required: true
        type: string
      cidr_block:
        description: 'CIDR Block'
        required: true
        type: string
      kubernetes_namespace:
        description: 'Kubernetes Namespace'
        required: true
        type: string
        default: 'e6data'
      terraform_state_key:
        description: 'Terraform State Key'
        required: true
        type: string
      s3_bucket:
        description: 'S3 Bucket for Terraform State'
        required: true
        type: string
      cost_tag_app:
        description: 'Cost Tag App Value'
        required: false
        type: string
        default: 'e6data'

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.5.7

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Inputs
        run: |
          if ! [[ "${{ github.event.inputs.workspace_name }}" =~ ^[a-z0-9]{3,10}$ ]]; then
            echo "Error: Workspace name must be 3-10 lowercase alphanumeric characters"
            exit 1
          fi
          if ! [[ "${{ github.event.inputs.cidr_block }}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$ ]]; then
            echo "Error: Invalid CIDR block format"
            exit 1
          fi
